# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/lumi-ds-project',
                'doc_host': 'https://lumiai.github.io',
                'git_url': 'https://github.com/lumiai/lumi-ds-project',
                'lib_path': 'lumi_ds_project'},
  'syms': {'lumi_ds_project.core': {'lumi_ds_project.core.foo': ('core.html#foo', 'lumi_ds_project/core.py')}}}
